### PR TITLE
Add way to style identifiers.

### LINKED ISSUE #147: Add way to style identifiers (i.e. schema, table, and column names)
As seen from the ‘getSegments’ tests, identifiers with backticks are classified as “string”, 

```js
it('complex query', () => {
  expect(getSegments("SELECT COUNT(id), `id`, `username` FROM `users` WHERE `email` = 'test@example.com' AND `foo` = 'BAR' OR 1=1"))
    .toStrictEqual([
      ...
      { name: 'string', content: '`email`' },
      ...
      { name: 'string', content: "'test@example.com'" },
```

That means that you can’t set a specific style for backticked identifiers, they just appear in the same color as strings.  In the example above, `` `email` `` and `'test@example.com'` end up with the same styling.

Furthermore, identifiers without backticks are lumped together with whitespace and identified as “default”.:

```js
it('test how default works', () => {
  expect(getSegments('SELECT * FROM hr.emp'))
    .toStrictEqual([
      { name: 'keyword', content: 'SELECT' },
      { name: 'default', content: ' ' },
      { name: 'special', content: '*' },
      { name: 'default', content: ' ' },
      { name: 'keyword', content: 'FROM' },
      { name: 'default', content: ' hr.emp' }
    ])
})
```

That means that (for example) you can’t set a `background-color` for identifiers like “hr.emp”, because then the `background-color` would apply to the whitespace before “hr.emp” too, in addition to the whitespace before and after the `*` character.

### PR DESCRIPTION
**Pull request by wkeese**
Replace "default" token with "whitespace" and "identifier" tokens, with fallback to "unknown" token.

Also, change backticked identifiers like `` `foo` `` to be classified as "identifier" rather than "string".

This allows for identifiers to be styled independently from strings and whitespace.

It also simplifies getSegments() from 30 lines down to 5, by removing the special-case code for the "default" token.

Fixes #147.

### CODE REVIEW

**Comment by scriptcoded** [comment]
Thanks, that was fast! All in all I think this is a good change, but I'll have to read through and check the code when I get the time.

Since this changes the public API this is considered a breaking change. You might see that the commit lint failed so please see the [contribution guidelines](https://github.com/scriptcoded/sql-highlight/blob/master/CONTRIBUTING.md) for information on the commit message format used. This also means you need to add something like the following footer to your commit:
```
BREAKING CHANGE: The `default` segment has been split into `string`, `whitespace` and `unknown`.
```

I'm wondering if there is some way of releasing this in a non-breaking fashion, but I don't think there is. I don't like pushing breaking changes too often so maybe it's time for me to have another look at how I manage releases so there can be a `next` experimental branch or something like that. I think it'd be good to start bunching these bigger changes together.

**Comment by wkeese** [comment]
Thanks.

> You might see that the commit lint failed so please see the [contribution guidelines](https://github.com/scriptcoded/sql-highlight/blob/master/CONTRIBUTING.md) for information on the commit message format used.

My bad on that one, I'll update the message.

> I'm wondering if there is some way of releasing this in a non-breaking fashion, but I don't think there is.

I've also been wondering about that.

The `highlight()` function works largely the same as before, both normal mode and HTML mode, except (what I consider to be) a bug fix to stop classifying identifiers as strings.   In other words, SQL like `select * from EMP where NAME="John Smith"` will get highlighted the same as before, i.e. no syntax highlighting for `EMP` or `NAME`.

But `getSegments()` does have some new output types (and loses the "default" output type), which could break some code.

**Comment by wkeese** [comment]
Anything you need from me on this?

**Comment by scriptcoded** [comment]
Hi again! I'm really sorry for letting you wait so long. Managing life, work and non-paid open source work can be a struggle sometimes. Should've left an update either way.

I've switched to using semantic-release for managing the package now which makes it possible to distribute using dist-tags on NPM. So I'll merge this to the `beta` branch.

I also took the liberty of adding `identifer` to the default colors and types myself and I'll be merging this using a squash instead. So if you feel good with these changes I'll merge this to the beta branch so you can start using it if you're dependent on these changes.

Thanks so much for your patience!

**Comment by wkeese** [comment]
> Hi again! I'm really sorry for letting you wait so long. Managing life, work and non-paid open source work can be a struggle sometimes. Should've left an update either way.

No worries, it seems like you're putting a lot of pressure on yourself with that scriptbot 2-week timer. :-)


> I also took the liberty of adding `identifer` to the default colors and types myself and I'll be merging this using a squash instead. So if you feel good with these changes I'll merge this to the beta branch so you can start using it if you're dependent on these changes.

Sure, looks good, I have no opinions about colors.

**Comment by scriptcoded** [comment]
> it seems like you're putting a lot of pressure on yourself with that scriptbot 2-week timer. :-)

I added it mostly to be able to close some issues that I didn't get responses on previously. But this time it came back to me :sweat_smile: Turns out it's a pretty good reminder.

Anyways, let's merge then! I'll come around to your other issues eventually!

**Pull request merged**
