### PR TITLE
Add RETURNING keyword

### PR DESCRIPTION
**Pull request by vladshcherbin**
https://www.postgresql.org/docs/current/dml-returning.html

### CODE REVIEW

**Comment by scriptcoded** [comment]
Thank you for contributing! To have the CI workflows work correctly, please make sure your commit messages follow the conventional commits format (https://www.conventionalcommits.org/en/v1.0.0/).

E.g. `fix: remove usage of hamster wheels for power generation`

If you've just made a single commit, using `git commit --amend` and force pushing works well.

**Comment by vladshcherbin** [comment]
@scriptcoded I've updated commit messages in both PRs 🙌

**Comment by scriptcoded** [comment]
Thanks! I'm gonna try something new and add these commits to the `next` branch and group these into one release. Fingers crossed this works 🤞

**Comment by vladshcherbin** [comment]
@scriptcoded thank you a lot for a quick release 🥳

**Pull request merged**
